site_name: UPL Documentation
nav:
  - Home: index.md
  - Types:
      - Power Types: power_types.md
  - Conditions:
      - Entity Conditions: entity_conditions.md
  - Actions:
      - Entity Actions: entity_actions.md
  - Miscellaneous:
      - Origins: misc/origins.md
      - Powers: misc/powers.md
      - Resource Bars: misc/resource_bars.md
      - Entities: misc/entities.md
      - Enchantments: misc/enchantments.md
      - Status Effects: misc/status_effects.md
theme:
  name: material
  features:
    - content.code.annotate 
  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FWEfASDYud
    - icon: fontawesome/brands/github
      link: https://github.com/UltrusBot/
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

separator: '_'